services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  websocket-server:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8081:8080'
    environment:
      - DB_HOST=postgres
      - DB_USER=wss_dev
      - DB_PASSWORD=postgres
      - DB_NAME=postgres

  http-server:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=postgres
      - DB_USER=api_dev
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
